name: 'Publish Stack Action'
description: 'GitHub action to publish stack'

inputs:
  client_id:
    description: Account client id
    required: true
  client_key:
    description: Account client key
    required: true
  realm:
    description: Account realm
    required: true
  studio:
    description: Studio name
    required: true
  stack_path:
    description: Stack Path
    required: false
    default: '.'    

runs:
  using: "composite"
  steps:
    - name: Download STK CLI
      shell: bash
      run: |
        curl \
          --fail \
          --http2-prior-knowledge \
          --location \
          --output /tmp/stk.deb \
          --silent \
          --show-error \
          --tlsv1.3 \
          https://stk.stackspot.com/installer/linux/stk.deb
        
    - name: Install STK CLI
      shell: bash
      run: |
        sudo dpkg --install /tmp/stk.deb || echo "Installation failed with exit code: $?"
        export PATH=$PATH:$HOME/.stk/bin

    - name: Verify if cli was installed
      shell: bash
      run: |
        dpkg -l | grep stk

    - name: Show STK CLI version
      shell: bash
      run: $HOME/.stk/bin/stk --version

    - name: Login StackSpot
      shell: bash
      env:
        CLIENT_ID: ${{ inputs.client_id }}
        CLIENT_KEY: ${{ inputs.client_key }}
        REALM: ${{ inputs.realm }}
      run: |
        $HOME/.stk/bin/stk login --client-id $CLIENT_ID --client-key $CLIENT_KEY --realm $REALM

    - name: Publish
      if: ${{ !contains(inputs.studio, 'UNPUBLISH_ACTION_TEST') }}
      shell: bash
      env:
        STUDIO: ${{ inputs.studio }}
        STACK_PATH: ${{ inputs.stack_path }}
      run: |
        cd $STACK_PATH
        if [ -f "stack.yaml" ] || [ -f "stack.yml" ]; then
          $HOME/.stk/bin/stk publish stack --studio $STUDIO
        else
          echo "No stack.yaml found"
        fi

    - name: Show Error Log
      shell: bash    
      if: ${{ failure() }}
      run: |
        cat $HOME/.stk/logs/*
        exit 1